# Alternative Read the Docs configuration (if you need more control)
# Uncomment and use this if the minimal config doesn't work

# version: 2

# # Set the OS, Python version and other tools you need
# build:
#   os: ubuntu-22.04
#   tools:
#     python: "3.11"
#   commands:
#     # Install dependencies
#     - pip install -r docs/requirements.txt
#     # Build documentation
#     - cd docs && sphinx-build -b html source _build/html

# # Build documentation in the "docs" directory with Sphinx
# sphinx:
#   configuration: docs/source/conf.py
